### ISSUE TITLE
JLoader::setup Strategy

### ISSUE THREAD

**Issue by romacron** [joomla/joomla-framework#126]
Perhaps i have misunderstood the setup part or the LoadByNamespace Strategy
Case: 
<?php 
error_reporting(E_ALL);
// Set the platform root path as a constant if necessary.
if (!defined('JPATH_PLATFORM'))
{
    define('JPATH_PLATFORM', **DIR**);
}

// Detect the native operating system type.
$os = strtoupper(substr(PHP_OS, 0, 3));

if (!defined('IS_WIN'))
{
    define('IS_WIN', ($os === 'WIN') ? true : false);
}
if (!defined('IS_UNIX'))
{
    define('IS_UNIX', (IS_WIN === false) ? true : false);
}

// Import the library loader if necessary.
if (!class_exists('JLoader'))
{
    require_once JPATH_PLATFORM . '/loader.php';
}

// Make sure that the Joomla Platform has been successfully loaded.
if (!class_exists('JLoader'))
{
    throw new RuntimeException('Joomla Platform not loaded.');
}

// Setup the autoloaders. (work only with namespaces as 'clear' joomla single packages)
JLoader::setup(JLoader::LOWER_CASE, true, false, false);

// have an folder inside called libs there are archive and filesystem taken from  
 joomla-framework-filesystem and  joomla-framework-archive
JLoader::registerNamespace('Joomla', JPATH_PLATFORM . '/libs');

// Dummy __construct
$archive=new Joomla\Archive\Archive();
?>

getting an Error because the Class is not found on Unix Systems
That results, the Filename is Archive.php (ucfirst)
- should i rename the files to lower cases?
- have i taken the wrong strategy?
- if there an JoomlaMasterStrategy/Convention to Load Classes 

thanx ;-)

**Comment by dongilbert** [comment]
There are some places in the documentation that have not been updated yet to reflect the new Composer based auto loading. Sorry you got linked to one of those places. 

If you install the framework via composer, then you can simply include vendor/autoload.php and start using the classes.
