### ISSUE TITLE
Installation Instructions in each package README

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#13]
We need a new doc to explain how people can install packages using Composer. This one is really important to get right and the instructions need to be clear and simple.

**Comment by eirslett** [comment]
Should it be one installation guide for each sub-package, or one for the whole framework?
Since the framework is modularised, I suppose the first one is better...

**Comment by dongilbert** [comment]
I would say add the docs/installation.md as the global. And then in each package README.md there should be a block that tells about using composer to install via `composer require joomla/packagename versionNumber` or by adding it to the composer.json of your project.

**Comment by dongilbert** [comment]
#99 takes care of the global docs/installation.md (just adds it to the README), but installation instructions still need to be added to each package README
