### ISSUE TITLE
Array to String Issues

### ISSUE THREAD

**Issue by elinw** [joomla/joomla-framework#138]
There are many exceptions that have array to string issues for things like $pks (I've been particularly finding them in JTableNested lately) that I've been fixing downstream.  Do you want those or is it just a waste of time and energy?

**Comment by realityking** [comment]
We don't have JTable in the framework anymore but any that apply to the classes still in the framework would be a great help.

**Comment by dongilbert** [comment]
I would agree anything that's still relevant in the Framework would be welcome. Thanks Elin!

**Comment by mbabker** [comment]
Do we have any issues left here?
