### ISSUE TITLE
Inconsistent element ID in JFormFieldUserGroup

### ISSUE THREAD

**Issue by stutteringp0et** [joomla/joomla-framework#140]
Adding some options to one my extensions, I found that the JFormFieldUserGroup field type generates an element ID that is inconsistent with other field types.

"usergroup" field type creates a concatenated ID string (no underscores) while other field types generate a consistent (underscored) ID.

Example:
<field type="usergroup" name="myUserGroup" ...>
generates this id: jformparamsmyUserGroup

For comparison:
<field type="accesslevel" name="myAccessLevel" ...>
generates this id: jform_params_myAccessLevel

I'm going to write detection and a workaround in my code, but consistent operation would be nice.

**Comment by dongilbert** [comment]
The Framework does not have the JFormFieldUserGroup; it was dropped because it was a very CMS specific form field. Please open this issue on the CMS.
