### ISSUE TITLE
JDatabaseMySQLi class does not support IPv6 MySQL server

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-framework#142]
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=30698

Know this isn't to do with the CMS anymore etc. etc. but this one you probably want to fix in the framework when there is a fix done :) To do with JDatabaseMySQLi class does not support IPv6 MySQL server

I've checked and the line in the namespace Joomla\Database\Mysqli still exists (also on line 110 currently as in the bug report)

**Comment by bweston92** [comment]
https://github.com/joomla/joomla-framework-database/pull/1

**Comment by mbabker** [comment]
Do we want to pull up [the fix the CMS](https://github.com/joomla/joomla-cms/commit/9fd1d58223fbade8a72ab7e2ec985bab2d72ca10) accepted here?

**Comment by bweston92** [comment]
It will require a test to be built/run.

**Comment by wilsonge** [comment]
This was fixed in fe570588d1817697b28b2e8695eac09ac5e1977b so closing
