### ISSUE TITLE
Module onLoad plugin.

### ISSUE THREAD

**Issue by bweston92** [joomla/joomla-framework#143]
I have some problems with dependencies. Basically I want to create a plugin that will allow me to specify a dependencies tree in the installation file of a module. This will then get read by my plugin and the appropriate dependencies (other modules) are imported.

How can this be made easy? I see no on load events for modules.

Thanks, Bradley.

**Comment by mahagr** [comment]
You mean during installation? In that case you can use install script to detect if those other extensions are installed and fail with enqueued message if not.

If you just want to know if another extension has been already loaded, then best way is probably to detect if a class has been loaded (works at least for components and plugins, but also for some modules which have helpers etc).

**Comment by bweston92** [comment]
Nope, like if I assign a module somewhere an it requires another module to be loaded also.
Basically I have a module with javascript in that is used in multiple places and would like it to be loaded only when a module with the dependency is required.

**Comment by mbabker** [comment]
If this is still an issue, please take it to the CMS.

**Comment by bweston92** [comment]
I was asking basically for like a Dependency Injection, which now is in the framework so all is good thanks.
