### ISSUE TITLE
JLoader improperly handles prefixes

### ISSUE THREAD

**Issue by genu** [joomla/joomla-framework#146]
``` php
private static function _autoload($class)
    {
        foreach (self::$prefixes as $prefix => $lookup)
        {
            $chr = strlen($prefix) < strlen($class) ? $class[strlen($prefix)] : 0;

            if (strpos($class, $prefix) === 0 && ($chr === strtoupper($chr)))
            {
                return self::_load(substr($class, strlen($prefix)), $lookup);
            }
        }

        return false;
    }

```

This logic doesn't take into consideration cases where prefixes beging with the same letters. So if I have a prefix **JBS**, and a class named **JBSLibFeature** then:

**$chr = 'L'**

and it would try to load the class from the wrong prefix, since **J** is part of the joomla library.

What is the point of the **$chr** here?

**Comment by mbabker** [comment]
JLoader has been dropped from the Framework as of this week.  If this is an issue that needs to be addressed, please raise it in [the CMS](https://github.com/joomla/joomla-cms) as it is still using this class.
