### ISSUE TITLE
Update @since to version 1.0

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#17]
We are reseting the entire Framework to version 1.0 so all `@since` tags need to be reset to 1.0. For example:

``` php
    /**
     * An instance of the class to test.
     *
     * @var    Joomla\Date\Date
     * @since  1.0
     */
    private $instance;
```

**Comment by dongilbert** [comment]
I might be able to handle this globally with `sed`.

**Comment by dongilbert** [comment]
Taken care of by 17cd53f47c3c45b0470c435180091933d9b12c51

**Comment by eddieajau** [comment]
Whoot.
