### ISSUE TITLE
Add a global function

### ISSUE THREAD

**Issue by elkuku** [joomla/joomla-framework#180]
This is about adding a global function.
Uhhh what ? (wtf).... No, please keep on reading ;)

**Benefits**
- Reduce the usage of **local variables**.
- Add **forward compatibility** for the PHP 5.4 feature [Class member access on instantiation](http://php.net/manual/en/migration54.new-features.php).

**Example**:
Plain PHP 5.3:

``` php
$class = new Class;
$result = $class->method();
```

Using the proposed `with()` function:

``` php
$result = with(new Class)->method();
```

Now when switching the minimum requirements to PHP 5.4 you simply change it to:

``` php
$result = (new Class)->method();
```

and remove the whole evil global function from the code base...

I hope, you can see the benefits.

What I am not quite sure about is to **where** would you add this global function ?

---

**Disclaimer**
This has been stolen from the Laravel framework and I am posting the whole magical function here, hoping that they won't prosecute me for copyright infringement ;)
From [laravel/framework/blob/master/src/Illuminate/Support/helpers.php#L869](https://github.com/laravel/framework/blob/master/src/Illuminate/Support/helpers.php#L869)

``` php
function with($object)
{
    return $object;
}
```

The power of simplicity :)

**Comment by dongilbert** [comment]
Love the forward compatibility idea there. :)
—

**Comment by mahagr** [comment]
Love the idea!

**Comment by Xerosigma** [comment]
Would this go in Compat?

**Comment by eddieajau** [comment]
:+1: but where to put it indeed. 

`/src/Joomla/PHP/helpers.php` ?

Might be able to use autoload "files"? 
http://getcomposer.org/doc/04-schema.md#autoload

**Comment by elkuku** [comment]
Thanks @eddieajau, that sounds like a plan &rArr; #216
