### ISSUE TITLE
Joomla is not able to connect to MySQL via named pipe (Windows).

### ISSUE THREAD

**Issue by tht2p** [joomla/joomla-framework#199]
I am trying to force Joomla! 3.x work using named pipe on Windows 7. Unfortunately, I am having hard time setting up named pipe with different from default name. I was trying to go deep into the Joomla’s framework, but was not able to solve the issue (lack of knowledge in programing). However, it seems to me that Joomla 3.x is able to connect to MySQL only via the default named pipe, i.e. “mysql”. Is that only a flaw of the system or a serious bug? I would appreciate if someone look into the issue.

**Comment by eddieajau** [comment]
You need to raise this in the joomla/joomla-cms repo and their bug tracker. Thanks.
