### ISSUE TITLE
Set up automatic subsplit when there's a merge to master

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#2]

**Comment by dongilbert** [comment]
I assigned Ian, as I think he has the server resources / access to set something up? Is this something you could do @ianmacl? I've created a webhook activated app that we could use as a base, or I know @mbabker did some work with web hooks in his tracker app.

**Comment by florianv** [comment]
I found this php script, it might be useful (didn't test it btw)

https://github.com/dflydev/dflydev-git-subsplit-github-webhook

**Comment by dongilbert** [comment]
It's what we use. Look at build/joomla-split.sh. We working on automating it with a post-receive hook.
