### ISSUE TITLE
Decoupled JText where possible

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#22]
We need to get JText out of the Framework as much as possible (the Form package is one exception in a few places). The exceptions or errors just need to be converted to natural language strings.

**Comment by realityking** [comment]
As far as I can tell JText is now only used in Form and Language. Can this be closed?

**Comment by mbabker** [comment]
I think we can.  The uses in Language are all documentation anyways, so the only true coupling is in Form.
