### ISSUE TITLE
What is the purpose of the $instance in AbstractCliApplication

### ISSUE THREAD

**Issue by asika32764** [joomla/joomla-framework#271]
I see a static variable in `AbstractCliApplication`

``` php
/**
 * @var    AbstractCliApplication  The application instance.
 * @since  1.0
 */
private static $instance;
```

but there are no `getInstance()` in this class.

Do we still need this variable?

**Comment by mbabker** [comment]
I don't believe so, all uses of a `getInstance()` method or the `$instance` static should have been refactored out.

**Comment by elkuku** [comment]
It's also present in the `AbstractWebApplication` - seems like a leftover..
