### ISSUE TITLE
Fatal error: Call to undefined method ReflectionProperty::setAccessible()

### ISSUE THREAD

**Issue by MDunkleSr** [joomla/joomla-framework#277]
Upgraded to Joomla 2.5.16.  Utilizing SQLSrv DB calls, the following breaking error is now reported:

Fatal error: Call to undefined method ReflectionProperty::setAccessible() in \libraries\joomla\database\database\sqlsrvquery.php on line 64

**Comment by eddieajau** [comment]
@MDunkleSr you'll need to log a bug with the CMS. Details are here:

http://developer.joomla.org/cms/report-an-issue.html

**Comment by MDunkleSr** [comment]
@eddieajau Thank you.  I can certainly file a bug in the issue tracker.  

I'm still trying to understand the process, there seem to be a lot of places to have to look.  I assumed that the Issue Tracker here would be the logical place to go.  Just wondering, why would this be filed against the CMS when it is a Framework library file that is throwing the error? 

Thanks!

**Comment by dongilbert** [comment]
It's not a Framework class, it's a Platform Class that has been taken over by the CMS. The only place where the Framework has been integrated so far is the DI container, and that's in 3.2 located in the `libraries/framework` folder.

**Comment by MDunkleSr** [comment]
I see.  Is there a place I can go to read up on the distinction? I don't contribute very regularly, but I want to figure out where I need to go when I find an issue that I can fix.

**Comment by dongilbert** [comment]
Well, almost all the code in the CMS is controlled by the CMS now, and will probably remain that way through the end of the 3.x series.

I would say always post the issue on the CMS repo. If it's framework related, we can create an issue here as well and link to the CMS one, but the CMS issue would still need to exist for tracking purposes anyways.

**Comment by eddieajau** [comment]
Once the new issue tracker is live, the confusion will **hopefully** be
reduced. I appreciate it can be hard to work out what goes where sometimes.

**Comment by elkuku** [comment]
> Once the new issue tracker is live, the confusion will **hopefully** be reduced.

The more hands and eyes we have, the sooner we'll get some results.
The project is here: https://github.com/joomla/jissues
