### ISSUE TITLE
Tests for new Cache package

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#29]
We've brought in the new Cache package that Louis Landry did a while back. Unfortunately it has not tests so these need to be done.

**Comment by florianv** [comment]
I find it generally nice to make it low level, but there are a few points, that I think can be improved :
- passing a JRegistry object as param makes it difficult to see which options are needed
- in the cache class, there is an array cache which, in my opinion, should be an handler itself
- the memcached handler would really like to take a Memcached instance as dependency
- handlers might implement an interface CacheHandlerInterface (basically containing all abstract methods of the current Cache class) + at least this method :

``` php
interface CacheHandlerInterface
{
   /** 
    * Checks if the handler supports serialization.
    *
    * @return  boolean  True if the handler supports serialization, false otherwise.
    */
   public function supportsSerialization();
}
```

The purpose of this method is simple, not all cache handlers supports serialization (ex : file, xcache) which means that if you want to persist an object in a portable way it needs to implement Serializable.

The purpose of this interface is to be proxied by a Cache class which would do the serialization job, before calling it to persist the data.(same thing for deserialization).
Also this cache class could allow a second handler  as fallback in case the main handler is unavailable, by default it could be the ArrayHandler.

``` php
class Cache
{
   protected $handler;

   public function setObject($key, Serializable $value, $ttl)
   {
      if (!$this->handler->supportsSerialization())
      { 
        $value = serialize($value);
      }

      $this->handler->set($key, $value, $ttl);
   }

   public function getObject($key)
   { 
     // Deserialization if the handler doesn't support it.
   }

  // Same stuff for arrays
}
```

**Comment by eddieajau** [comment]
Test skeletons added.

@florianv I think this is going to be the next PSR for Cache: https://github.com/dlsniper/fig-standards/blob/cache-proposal/proposed/psr-cache.md

We haven't voted yet and there are two other variations but I think that is the favourite.

> in the cache class, there is an array cache which, in my opinion, should be an handler itself

I'm open to suggestions how to have that working better. Basically the idea is to track what objects are already in memory. To be honest, it probably only affects the performance of the File cache so you are probably right, Runtime should be its own handler.

**Comment by florianv** [comment]
@eddieajau The proposal looks nice but I think this is a bit raw. Also, I don't get the purpose of a cache item : I believe it represents a Cache entry but this is a bit overkill to have one object per entry.

**Comment by eddieajau** [comment]
You are welcome to comment on the FIG mailing list if it's something you are interested in.

**Comment by florianv** [comment]
Hum yes could be a possibility. I think they could take some inspiration from http://gregluck.com/blog/archives/2011/10/javax-cache-the-new-java-caching-standard/

**Comment by florianv** [comment]
I did make a comment but it got ignored.

I don't think wrapping the apc functions in an interface can become a cache standard to be honest.

None of the given proposal clearly define how to solve the serialization problem.
Because there is no way to know if an object or array is stored at a given key, you need to unserialize all returned strings to see if it was a serialized object or array (which is really not good).

Also, the "set" method should throw an exception if a passed object is not Serializable.

Moreover I don't get the purpose of a CacheItem if it's just to hold a value, then php variables are fine too :P

**Comment by eddieajau** [comment]
Ref https://github.com/joomla/joomla-framework/commit/fd0b4757170cb4fb9edbc13b87b6aa1903aebf8f

**Comment by florianv** [comment]
Im looking at doctrine cache.

https://github.com/doctrine/cache

They have quite the same implementation than us but more handlers and it's tested.

**Comment by eddieajau** [comment]
I was looking at that heavily yesterday. I wish the Cache PSR would hurry up :)

My only concern is that it does not look to be well tested. So I think we can each roll our own full tested and documented version of cache, or we help Doctrine improve theirs?

**Comment by florianv** [comment]
Yes I think that could be a good idea.
They have some tests, maybe the case when it expires could be added (they have it in Memcache).

**Comment by eddieajau** [comment]
I've worked pretty hard on the Cache package today. I'm going to stick with it for a while longer because Doctrine's test coverage is no better than what we have, and also I can tune our package to be natively Psr\Cache compliant. I hope to have a branch up tomorrow to review.

**Comment by florianv** [comment]
ok :) Yes it's also good to have the possibility to change it dependending on what will happen with the cache competition.

**Comment by eddieajau** [comment]
Oh, and the Doctrine\Cache tests wouldn't run standalone :)
