### ISSUE TITLE
[Database] Driver date format

### ISSUE THREAD

**Issue by florianv** [joomla/joomla-framework#30]
I saw JDate::toSql has been removed which is good, but I don't see a replacement yet

We should have a method like  :

``` php
public function formatDate(DateTime $date);
```

in the drivers.

**Comment by florianv** [comment]
This kind of stuff doesn't really belong to drivers but there is no place where it would fit otherwise.

**Comment by mbabker** [comment]
`JDate::toSql()` called `$db->getDateFormat()`, which is present in the database drivers.

**Comment by florianv** [comment]
I missed it thanks.

**Comment by eddieajau** [comment]
No worries :)
