### ISSUE TITLE
Twitter Object constructor problem

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#300]
Travis is reporting a problem with this file

https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Twitter/Object.php#L48

> Arguments with default values must be at the end of the argument list.

Ideally it should be at the end but that cause a b/c problem. How should we fix?

**Comment by dongilbert** [comment]
I do not view it as a BC break, because the class requires you to pass the options array as well as the other two mandatory params in order to use it. I would make it mandatory by removing `= array()`.

**Comment by eddieajau** [comment]
Removing array() works for me.
