### ISSUE TITLE
Remove coupling to JFactory

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#32]
We need to remove the coupling to the old JFactory, now \Joomla\Factory.
- [x] Application
- [x] Archive
- [x] Client
- [x] Controller
- [x] Filesystem
- [x] Filter
- [x] Form
- [x] Http
- [x] Language
- [x] Log
- [x] Model
- [x] OAuth1
- [x] OAuth2
- [x] Session

**Comment by dongilbert** [comment]
So would the basic thought on this be that in cases where the Factory::getXXXXXX method is just a wrapper for specific `getInstance()` (as in the case of `Database\Driver`) that we just drop it in favor of the `getInstance` method for that class?

The only downside of that approach is in the case of `Database\Driver::getInstance()` it requires you to pass it a config, which is handled by Factory. So, currently there is no dependency within the `Driver::getInstance()` method, but if we switch to doing it as described above, then we create a `Config` dependency.

Not sure what to do.

**Comment by eddieajau** [comment]
So I think in the case of JFactory::getDbo we replace that with the database factory where we know we have the configuration for the database. If we can't guarantee that we will have configuration, then we should rely only on dependancy injection. Application handles configuration so I think we require a node and a format for the database credentials and from there we can safely support `loadDatabase`. Does that make sense?

**Comment by piotr-cz** [comment]
After @mbabker 's patch, Packages using `JLanguage::getInstance()` like `Text::_('TRANSLATE')` are always [falling back to default language](https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Language/Language.php#L191).

There's no place where current language is stored (was `Factory::$language` before).
I described the problem at the [Framework group](https://groups.google.com/forum/#!topic/joomla-dev-framework/cEQEJRPo1-E) but have no idea how to handle this.

**Comment by dongilbert** [comment]
I did a search, and of the remaining methods in `Factory`, only these usages remain:

``` php
// Places that reference: Factory::getDbo()
docs/coding-standards/php.md
src/Joomla/Database/README.md
src/Joomla/Form/Field/Sql.php
src/Joomla/Form/Rule/Email.php
src/Joomla/Language/LanguageHelper.php
src/Joomla/Log/Logger/Database.php
src/Joomla/Session/Storage/Database.php

// Places that reference: Factory::getConfig()
src/Joomla/Form/Field/Timezone.php
src/Joomla/Form/Form.php
src/Joomla/Form/Tests/JFormTest.php
src/Joomla/Log/Logger/Formattedtext.php
src/Joomla/Session/Session.php
src/Joomla/Session/Storage/Memcache.php
src/Joomla/Session/Storage/Memcached.php

// Places that reference: Factory::getsession()
src/Joomla/Oauth1/Client.php
src/Joomla/Session/Session.php

// Places that reference: Factory::$application
src/Joomla/Oauth2/Client.php
src/Joomla/Session/_Tests/JSessionTest.php
```

**Comment by dongilbert** [comment]
Oops, forgot about `Factory::getStream()` (it's not been removed, yet)

```
src/Joomla/Archive/Bzip2.php
src/Joomla/Archive/Gzip.php
```

**Comment by dongilbert** [comment]
Once #238 is merged, we can check off Form.

**Comment by dongilbert** [comment]
Once #239 is merged, we can check off Language.

**Comment by dongilbert** [comment]
Once #241 is merged, we can check off Session.

**Comment by dongilbert** [comment]
Once #244 is merged, we can check off Oauth 1 & 2.

**Comment by dongilbert** [comment]
Once #242 is merged, we can check off Log. And that will be the last of them.

**Comment by piotr-cz** [comment]
I think the solution for `Text` is to set the `Language` instance, otherwise it will [always pull the default one](https://github.com/joomla/joomla-framework/blob/staging/src/Joomla/Language/Text.php#L45).
(or convert it to instance and provide `$language` in constructor)

``` PHP
class Text
{
    protected static $lang;

    public static function setLanguage(Language $lang)
    {
        static::$lang = $lang;
    }

    public static function _($string, $jsSafe = false, $interpretBackSlashes = true, $script = false)
    {
        $lang = self::$lang;

        //...
    }
}
```

and then

``` PHP
// In application
$language = Language::getInstance('pl-PL');
Text::setLanguage($lang);

// Later on
echo Text::_('HELLO_WORLD');
```

**Comment by dongilbert** [comment]
That's a reasonable approach, @piotr-cz
