### ISSUE TITLE
DatabaseQuery lacks dateAdd() and unionAll()

### ISSUE THREAD

**Issue by betweenbrain** [joomla/joomla-framework#328]
I was just doing a comparison of the CMS's JDatabaseQuery class versus the framework's DatabaseQuery class and it seems that they are nearly identical (from a functionality perspective) but DatabaseQuery lacks the dateAdd() and unionAll() functions found in the CMS. Was this on purpose or something that didn't get pushed upstream to the framework maybe?

**Comment by dongilbert** [comment]
Those were both added in March 2013, after the initial fork of the Framework from the CMS. They should probably be added.

However, I'm not sure about the syntax of the method. It looks like the one in the CMS is targeted at MySQL (given the reference to the mysql docs in the DocBlock), so I'm not sure if it should be an abstract method, and then each driver to have it's own implementation.
