### ISSUE TITLE
Problem with permission Guest

### ISSUE THREAD

**Issue by daniel2014** [joomla/joomla-framework#338]
I'm having trouble when I use the guest Perm doing a menu disappear when the user is logged this function does not work in the version of joomla 3.2 I tested in version 3.1 and works normally but it is possible that it works when I do the upgrade from joomla 3.2 3.1para but nothing compared to when an installation is made the latest version of joomla. Anyone know how to solve this problem?

**Comment by eddieajau** [comment]
I'm sorry but we can't help with that question. You can posting the question on the [Joomla Forum](http://forum.joomla.org) or possibly [StackOverflow](http://stackoverflow.com/questions/tagged/joomla).
