### ISSUE TITLE
Document ArrayHelper

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#35]
The `ArrayHelper` class needs to be documented.

Tasks:
1. Add a brief example of how to use each method in the `ArrayHelper` class.

References:
https://github.com/joomla/joomla-framework/blob/master/vendor/Joomla/Utilities/README.md

**Comment by eirslett** [comment]
I'll have a go at this one if nobody else is doing it already!

**Comment by dongilbert** [comment]
I'm not working on it, and no one else has mentioned they are, so go ahead and go for it! :+1:

**Comment by eirslett** [comment]
``` php
class Book { ... }

$input = array(
    "name" => "The Hitchhiker's Guide to the Galaxy",
    "author" => array(
        "name" => "Douglas Adams",
        "born" => 1952,
        "died" => 2001),
    "genre" => "comic science fiction",
    "rating" => 10
);
$book = ArrayHelper::toObject($input, 'Book');

print_r($book);
```

```
Book Object
(
    [name] => The Hitchhiker's Guide to the Galaxy
    [author] => Book Object
        (
            [name] => Douglas Adams
            [born] => 1952
            [died] => 2001
        )

    [genre] => comic science fiction
    [rating] => 10
)
```

Is this really the desired behavior? Letting "author" field become a Book object too? How about changing it, so it always converts subdimension-arrays to stdClass?

**Comment by eirslett** [comment]
By the way, why is ArrayHelper declared as an abstract class with only public static fields and methods (except for one protected method)? Is it supposed to be extended by other classes? MyExtension\BetterArrayHelper extends ArrayHelper?

Wouldn't it be better to 1) declare ArrayHelper final instead of abstract, 2) declare a private constructor to disallow instantiation, and 3) make the protected method private?

**Comment by eddieajau** [comment]
> Is this really the desired behavior?

I'm happy if you just document the actual behaviour for now. Changing the behaviour is something that can follow later.

> why is ArrayHelper declared as an abstract class

We don't have the ability to declare a class "static" so often, when we don't want a class to be instantiated, we'll make it abstract. Having said that, this is an old class and I think if we did it again we'd make an `ArrayObject` class, probably extended from SPL.
