### ISSUE TITLE
Support for PSR-4 autoloading

### ISSUE THREAD

**Issue by piotr-cz** [joomla/joomla-framework#353]
Composer supports PSR-4 autoloading since beginning of January 2014.

What it means for the Framework: packages may be moved directly into `src/` subfolder.

References:
- [blogpost](http://seld.be/notes/psr-4-autoloading-support-in-composer)
- [documentation](https://getcomposer.org/doc/04-schema.md#psr-4)

**Comment by mbabker** [comment]
Most of the individual packages have been converted to PSR-4 standard in their new home (https://github.com/joomla-framework).  This repo is being phased out, so you won't see many more changes here.

**Comment by piotr-cz** [comment]
Thanks. Where can I find the information about the github changes? [framework.joomla.org](http://framework.joomla.org/) is still pointing here.

**Comment by mbabker** [comment]
We still need to publish a post from the Architecture Sprint most of the
Framework team participated in a couple weekends ago.  I'll work on getting
that site updated.

**Comment by mbabker** [comment]
Site's updated for the most part.  There's still two links pointing to this repo (report an issue with the site and the CONTRIBUTING file), otherwise that's good to go for now.
