### ISSUE TITLE
Error in Language::__construct

### ISSUE THREAD

**Issue by jbanety** [joomla/joomla-framework#363]
Language does not load the language localise script (e.g. fr-FR.localise.php).

In `Language::__construct` (at line 215)

``` php
$basePath = self::getLanguagePath(JPATH_ROOT);
$paths[0] = $basePath . "/language/overrides/$lang.localise.php";
$paths[1] = $basePath . "/language/$lang/$lang.localise.php";
```

It calls `getLanguagePath()` which does : 

``` php
$dir = $basePath . '/language';
```

So Language is looking for localise script in folder : JPATH_ROOT/language/language/fr-FR/fr-FR.localise.php => double "language".

I fixed it with (lines 217 and 218) : 

``` php
$paths[0] = $basePath . "/overrides/$lang.localise.php";
$paths[1] = $basePath . "/$lang/$lang.localise.php";
```

**Comment by mbabker** [comment]
Fixed years ago in the language package repo.
