### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Wakinya** [joomla/joomla-framework#368]
In J 3.3.3 admin> Category Manager> Categories when I set the visible number of categories using the button on the top rhs to "All" and then try to modify ordering by using drag n drop I get an error:

" Warning: Unresponsive Script 
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
Script: http://localhost:mysite/media/jui/js/jquery.min.js:3 mysite/media/jui/js/jquery.min.js:3  "

The page then freezes and I have to restart.

It happens on all browsers.

On the other settings eg 5; 10; 15; 20; 25; 30; 50 and 100, drag n drop works as usual.

My project is in early stages and I tried troubleshooting by disabling and/ or uninstalling several extensions but this persists.

As I recall it worked ok when I had only a few entries but after about 200 entries this issue began. (This never happened on a similar project on J 2.5)

I'm not sure if this symptom is, a) to be expected, b) a conflict with an extension, c) something else or whether its something I've done or was there all the time. Or whether it is an error or warning.

I have no idea how to debug jquery and I'm reluctant to start fiddling until I have at least half a clue what I may be doing.
'Stop Script' fails.
'Continue 'also fails.

And the browser freezes.

Project isd on MAMP local host in development in Joomla v 3.3.3.

Is anyone else experiencing this?

What is the best course of action? (Other than not using the  "All" setting)

Thank you,

Nev

I've attached a screenshot of the pop up.
![screen shot 2014-09-07](https://cloud.githubusercontent.com/assets/8686010/4178319/1e876310-368e-11e4-988e-65d6ab560960.png)

**Comment by mbabker** [comment]
Hi,

This is an issue for the Joomla! CMS.  Please report your issue at http://issues.joomla.org.
