### ISSUE TITLE
Update Composer package

### ISSUE THREAD

**Issue by abemedia** [joomla/joomla-framework#369]
When installing the Joomla Framework in Composer it installs the 1.1 version for all packages, even if they have newer versions available. As a result it's not possible for me to deploy my dependencies with an action hook to Composer as there's bugs which have already been fixed in sub-packages.

I suggest having the packages as separate Composer packages (like Symfony) or, even better, coming up with some magical webhook that updates the main framework package each time one of the sub-packages gets a new release.

**Comment by mbabker** [comment]
Each of the packages is available separately (https://packagist.org/packages/joomla/) and is recommended over using `joomla/framework` as their repos aren't sync'd to this main repo.

**Comment by abemedia** [comment]
Whoops... Had tried it and and I thought it hadn't worked as I was still requiring the whole framework as well. In my defence it was 3am :smile:
