### ISSUE TITLE
Which PHP version to use?

### ISSUE THREAD

**Issue by eirslett** [joomla/joomla-framework#37]
I saw composer.json specified PHP version 5.3.10 as a minimum requirement for Joomla Framework. Why is this the exact version? Why not 5.3.9 or 5.3.11? Why not go all the way and use 5.4.x, which was released right after 5.3.10?

See also #36

**Comment by eirslett** [comment]
Ok sorry, got my answers in #36

**Comment by mbabker** [comment]
Feel free to ask questions as needed.  We're all pretty good about explaining the reasoning about why we are doing things the way we are.
