### ISSUE TITLE
Replace MySQL driver with PDO version

### ISSUE THREAD

**Issue by eddieajau** [joomla/joomla-framework#82]
See Ian's code here:
https://github.com/joomla/joomla-platform/pull/1403

**Comment by eddieajau** [comment]
@ianmacl FYI

**Comment by dongilbert** [comment]
Fixed by #218

**Comment by AmyStephen** [comment]
Excellent work @asika32764

**Comment by asika32764** [comment]
@AmyStephen Thank you. :)
